### ISSUE TITLE
Tracks Linked skills break if more than one added

### ISSUE THREAD

**Issue by jsavko** [Sk1mble/modularFate#11]
I was attempting to setup the core book skills with physique and will modifying physical/mental stress track with +1 box at +1 skill and +2 boxes at +3 skill. When you add both rules the stress track no longer will render on the character sheet.  As long as only one rule is present the track works as intended.

**Comment by Sk1mble** [comment]
I've just tested with a brand new world and this is working as expected. I suspect you have ticked the 'enables' box in the configuration, which is incorrect - the 'enables' box means that the track is turned off unless the criterion in the rule is present. Here is what it should look like:

![image](https://user-images.githubusercontent.com/1439478/113364236-e55ef280-934a-11eb-9f83-b0fecdcf7910.png)

**Comment by Sk1mble** [comment]
![image](https://user-images.githubusercontent.com/1439478/113364281-ff003a00-934a-11eb-9deb-d0acfa00176e.png)
![image](https://user-images.githubusercontent.com/1439478/113364296-06bfde80-934b-11eb-9bbc-d7523135e57c.png)
