### ISSUE TITLE
[Suggestion] Allowing Situation Aspects to be movable

### ISSUE THREAD

**Issue by wishinghand** [Sk1mble/modularFate#15]
When making Situation Aspects with the Fate Utilities, they're stuck in one place. Would love it if after setting them using FU, they could be dragged around the scene, as well as the size being adjustable.

**Comment by Sk1mble** [comment]
Aspect labels on the map are Foundry drawings on the drawing layer and can
be moved or resized from there.

That's the pencil icon in the list of tools on the left hand side.

Richard
