### ISSUE TITLE
[Bug] Cannot Create or Import Skills from Scratch

### ISSUE THREAD

**Issue by scottmk** [Sk1mble/modularFate#16]
When you create a new world, if you try to create new skills from scratch, the dialog comes up, but the values are not saved and persisted.

Similarly, if you try to import skills as as JSON string, you get an error:

`TypeError: cannot create property 'Athletics' on string "`,

which implies that skills can only be replaced with the import method, and not created.

The only way I can get anything to work is to start with a default list of skills and edit them.

**Comment by Sk1mble** [comment]
Hi, Modular Fate is no longer supported as it has been replaced with Fate
Core Official. Are you running a version of Foundry less then 0.8? Modular
Fate is only compatible with Foundry up to 0 7.9.

**Comment by scottmk** [comment]
I apologize; I didn't realize this had been replaced with FateCoreOfficial, and just figured that out right as you responded. Thanks for the quick response!
