### ISSUE TITLE
Feature request regarding Description and Biography fields

### ISSUE THREAD

**Issue by doct** [Sk1mble/modularFate#4]
Can you please make the Description and Biography fields editable with the WYSIWYG editor, so that text can be nicely formatted and even images included? Thanks!

**Comment by Sk1mble** [comment]
No plans to introduce this, sorry.

However, those fields do support basic rich text in the format of **bold**, _Italic_, and underline. You can access these with the usual keyboard shortcut (e.g. ctrl-b for bold on Windows).

These fields are meant to be for brief synopses, not massively in-depth articles about the characters. If you want to have richer text or images for the character bio etc. I suggest that journal entries are better suited to that.
