### ISSUE TITLE
Feature Request: Usability of Stunts

### ISSUE THREAD

**Issue by doct** [Sk1mble/modularFate#5]
Currently, to roll a stunt you have to hit the finicky roll icon. That however is only a few pixels away from the trash can icon, which upon accidental clicking deletes the stunt from the character without hesitation.

Can you please 
a) add a confirmation dialog to deleting a stunt from the character,
b) make clicking the stunt name bar area rolling for the stunt, just like it currently is with skills?

That would make using stunts way easier and less dangerous.

Thanks for your great system module!

**Comment by Sk1mble** [comment]
I don't currently plan to throw up a confirmation dialogue before deleting stunts. I may tweak the layout so there's a larger gap between the roll button and the delete button.
If you're worried, you can ensure you've backed up character stunts to the stunts database. You can also roll stunts from the FateUtilities window from the drop-down skill list for each character, or by shift-clicking on a character's skill to bring up the modified roll dialog.

**Comment by Sk1mble** [comment]
I've added a user-scope setting to the System settings window to set whether the system should request confirmation before deleting anything with a trashcan icon. This is live in v1.7.7.

**Comment by doct** [comment]
Amazing, works fine, thank you!
