### ISSUE TITLE
Feature Request: Usability of skill entrires

### ISSUE THREAD

**Issue by doct** [Sk1mble/modularFate#6]
Currently, clicking the bar are of a skill rolls for the skill, just the same as clicking the roll icon does, too.
However, a common question about skills is, what do they do and what actions do they have.
Luckily, this can question can be answered by clicking the gear icon, then clicking on the name of the skill. A new "Skill Details" window opens, which is great.
It would be really nice, if that skill window would be more accessible while looking the skill list on the char sheet. E.g., clicking on the name or name bar of the skill could open that "Skill Details" window. Or their were another "Info" icon beside the roll icon to show the dialog. Or maybe show a hoover-over dialog if that is possible. Or any other way to show the skill details with just one click.
Thanks you again!

**Comment by Sk1mble** [comment]
This will be included in release 1.7.5.

**Comment by Sk1mble** [comment]
I've just pushed this update.

**Comment by doct** [comment]
Right-clicking on a skill now shows the Skill Details dialog, awesome! Thank you!
