### ISSUE TITLE
"Create an Advantage" header missing on skill description in Skill Editor

### ISSUE THREAD

**Issue by Tynam** [Sk1mble/modularFate#8]
The **Create an Advantage:** title is missing from skill descriptions, *only if* they are accessed by entering the game skill editor (such as from a character sheet) and clicking the skill name.  The rules text for the skill appears correctly; it's only the actual words **Create an Advantage:** that are missing.

If the description is accessed by right-clicking the skill on a character sheet, the title appears correctly.

Priority estimate: This is so minor I don't even have a phrase for how minor it is.

**Comment by Sk1mble** [comment]
Hi, are you sure? If you mean here, it's working for me:

![image](https://user-images.githubusercontent.com/1439478/106528411-a2b2a280-64e0-11eb-9d1a-a0f70f80760b.png)

**Comment by Tynam** [comment]
Sorry, I wasn't clear.  Header is showing correctly in the skill editor screen for the module, but not if a player reads the skill description by opening the _character's_ skill editor and clicking the skill name.

Skill description by right-clicking the skill on the character sheet:

![Fate modular 8 correct](https://user-images.githubusercontent.com/4976043/106529746-eefee200-64e2-11eb-85f3-1b8eec545135.jpg)

Skill description by clicking the gear for the character skill editor, and clicking the name there:

![Fate modular 8 incorrect](https://user-images.githubusercontent.com/4976043/106529788-fe7e2b00-64e2-11eb-8e33-366d24b7c7d5.jpg)

(I created a blank world with the default Fate Core skill list just to test I hadn't broken anything myself; same result.)
Hope that helps.

(And thanks for your incredible work on this system; we're having much fun because of it.)

**Comment by Sk1mble** [comment]
Thank you for the more detailed description. An angular bracket had gone missing on the HTML to show that window, so it wasn't displaying at all. I've just fixed this and will push an update later.

I'm glad you're enjoying it! I'm pushing a couple more bug fixes soon too.
